# Generated by Django 5.1.8 on 2026-08-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0024_volumeoperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupjob',
            name='max_size',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
