#!/usr/bin/env python3
"""Build the small, dependency-free JavaScript bundles used by Django templates."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parent.parent


@dataclass(frozen=True)
class Bundle:
    target: str
    selector: str
    guard: str
    sources: tuple[str, ...]


BUNDLES = (
    Bundle(
        target="static/monitor/dist/file_manager.bundle.js",
        selector='[data-file-manager-page]',
        guard="!page",
        sources=(
            "static/monitor/js/file_manager/core.js",
            "static/monitor/js/file_manager/actions.js",
            "static/monitor/js/file_manager/browser.js",
            "static/monitor/js/file_manager/information.js",
            "static/monitor/js/file_manager/preview.js",
            "static/monitor/js/file_manager/transfers.js",
            "static/monitor/js/file_manager/uploads.js",
            "static/monitor/js/file_manager/downloads.js",
            "static/monitor/js/file_manager/destination.js",
        ),
    ),
    Bundle(
        target="static/monitor/dist/web_terminal.bundle.js",
        selector="[data-terminal-page]",
        guard="!page || !window.Terminal || !window.FitAddon",
        sources=(
            "static/monitor/js/web_terminal/core.js",
            "static/monitor/js/web_terminal/websocket.js",
            "static/monitor/js/web_terminal/session.js",
            "static/monitor/js/web_terminal/fallback.js",
            "static/monitor/js/web_terminal/mobile.js",
        ),
    ),
)


def render(bundle: Bundle) -> str:
    body = "".join((ROOT / source).read_text(encoding="utf-8") for source in bundle.sources).rstrip("\n")
    return (
        "// Generated by tools/build_frontend_bundles.py. Do not edit directly.\n"
        "(function () {\n"
        f'  const page = document.querySelector("{bundle.selector}");\n'
        f"  if ({bundle.guard}) return;\n\n"
        f"{body}\n"
        "})();\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if a generated bundle is absent or stale")
    args = parser.parse_args()

    stale: list[str] = []
    for bundle in BUNDLES:
        target = ROOT / bundle.target
        expected = render(bundle)
        if args.check:
            if not target.exists() or target.read_text(encoding="utf-8") != expected:
                stale.append(bundle.target)
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        temporary = target.with_suffix(f"{target.suffix}.tmp")
        temporary.write_text(expected, encoding="utf-8")
        temporary.replace(target)

    if stale:
        print("Stale frontend bundles: " + ", ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
