#!/usr/bin/env python3
"""Build dependency-free JavaScript and CSS bundles used by Django templates."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parent.parent


@dataclass(frozen=True)
class Bundle:
    target: str
    selector: str
    guard: str
    sources: tuple[str, ...]


@dataclass(frozen=True)
class StylesheetBundle:
    target: str
    sources: tuple[str, ...]


BUNDLES = (
    Bundle(
        target="file_manager_app/static/file_manager_app/dist/file_manager.bundle.js",
        selector='[data-file-manager-page]',
        guard="!page",
        sources=(
            "file_manager_app/static/file_manager_app/js/file_manager/core.js",
            "file_manager_app/static/file_manager_app/js/file_manager/actions.js",
            "file_manager_app/static/file_manager_app/js/file_manager/browser.js",
            "file_manager_app/static/file_manager_app/js/file_manager/information.js",
            "file_manager_app/static/file_manager_app/js/file_manager/video.js",
            "file_manager_app/static/file_manager_app/js/file_manager/preview.js",
            "file_manager_app/static/file_manager_app/js/file_manager/transfers.js",
            "file_manager_app/static/file_manager_app/js/file_manager/uploads.js",
            "file_manager_app/static/file_manager_app/js/file_manager/downloads.js",
            "file_manager_app/static/file_manager_app/js/file_manager/destination.js",
        ),
    ),
    Bundle(
        target="terminal_app/static/terminal_app/dist/web_terminal.bundle.js",
        selector="[data-terminal-page]",
        guard="!page || !window.Terminal || !window.FitAddon",
        sources=(
            "terminal_app/static/terminal_app/js/web_terminal/core.js",
            "terminal_app/static/terminal_app/js/web_terminal/websocket.js",
            "terminal_app/static/terminal_app/js/web_terminal/session.js",
            "terminal_app/static/terminal_app/js/web_terminal/fallback.js",
            "terminal_app/static/terminal_app/js/web_terminal/mobile.js",
        ),
    ),
)

STYLESHEET_BUNDLES = (
    StylesheetBundle(
        target="main_app/static/main_app/dist/app.bundle.css",
        sources=(
            "main_app/static/main_app/css/shell.css",
            "monitor_app/static/monitor_app/css/monitor.css",
            "volumes_app/static/volumes_app/css/volumes.css",
            "monitor_app/static/monitor_app/css/memory.css",
            "main_app/static/main_app/css/settings.css",
            "alerts_app/static/alerts_app/css/feed.css",
            "reports_app/static/reports_app/css/reports.css",
            "main_app/static/main_app/css/path_browser.css",
            "backups_app/static/backups_app/css/editor.css",
            "jobs_app/static/jobs_app/css/lists.css",
            "docker_runtime_app/static/docker_runtime_app/css/docker.css",
            "backups_app/static/backups_app/css/jobs.css",
            "alerts_app/static/alerts_app/css/rules.css",
            "history_app/static/history_app/css/history.css",
            "jobs_app/static/jobs_app/css/runs.css",
            "backups_app/static/backups_app/css/runs.css",
            "jobs_app/static/jobs_app/css/editor.css",
            "main_app/static/main_app/css/responsive-components.css",
            "main_app/static/main_app/css/forms.css",
            "terminal_app/static/terminal_app/css/terminal.css",
            "file_manager_app/static/file_manager_app/css/layout.css",
            "users_app/static/users_app/css/users.css",
            "main_app/static/main_app/css/home.css",
            "file_manager_app/static/file_manager_app/css/shares.css",
            "file_manager_app/static/file_manager_app/css/browser-shell.css",
            "file_manager_app/static/file_manager_app/css/browser-items.css",
            "file_manager_app/static/file_manager_app/css/transfers.css",
            "file_manager_app/static/file_manager_app/css/uploads-search-downloads.css",
            "file_manager_app/static/file_manager_app/css/preview.css",
            "file_manager_app/static/file_manager_app/css/information.css",
            "main_app/static/main_app/css/responsive-pages.css",
        ),
    ),
)


def render(bundle: Bundle) -> str:
    body = "".join((ROOT / source).read_text(encoding="utf-8") for source in bundle.sources).rstrip("\n")
    return (
        "// Generated by tools/build_frontend_bundles.py. Do not edit directly.\n"
        "(function () {\n"
        f'  const page = document.querySelector("{bundle.selector}");\n'
        f"  if ({bundle.guard}) return;\n\n"
        f"{body}\n"
        "})();\n"
    )


def render_stylesheet(bundle: StylesheetBundle) -> str:
    body = "".join((ROOT / source).read_text(encoding="utf-8") for source in bundle.sources).rstrip("\n")
    return "/* Generated by tools/build_frontend_bundles.py. Do not edit directly. */\n" + body + "\n"


def build(*, check: bool = False) -> int:
    """Generate all frontend bundles, optionally checking freshness only."""
    stale: list[str] = []
    assets = tuple((bundle.target, render(bundle)) for bundle in BUNDLES)
    assets += tuple((bundle.target, render_stylesheet(bundle)) for bundle in STYLESHEET_BUNDLES)
    for target_name, expected in assets:
        target = ROOT / target_name
        if check:
            if not target.exists() or target.read_text(encoding="utf-8") != expected:
                stale.append(target_name)
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        temporary = target.with_suffix(f"{target.suffix}.tmp")
        temporary.write_text(expected, encoding="utf-8")
        temporary.replace(target)

    if stale:
        print("Stale frontend bundles: " + ", ".join(stale), file=sys.stderr)
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if a generated bundle is absent or stale")
    args = parser.parse_args()
    return build(check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
