import unittest

import build_frontend_bundles as builder


class FrontendBundleTests(unittest.TestCase):
    def test_sources_are_small_and_owned_by_one_bundle(self):
        seen = set()
        for bundle in builder.BUNDLES:
            self.assertTrue(bundle.sources)
            for source_name in bundle.sources:
                self.assertNotIn(source_name, seen)
                seen.add(source_name)
                source = builder.ROOT / source_name
                self.assertTrue(source.is_file(), source_name)
                self.assertLessEqual(len(source.read_text(encoding="utf-8").splitlines()), 600, source_name)

    def test_render_is_deterministic_and_wraps_sources_in_order(self):
        for bundle in builder.BUNDLES:
            rendered = builder.render(bundle)
            self.assertEqual(rendered, builder.render(bundle))
            self.assertTrue(rendered.startswith("// Generated by tools/build_frontend_bundles.py."))
            positions = []
            for source_name in bundle.sources:
                first_nonempty = next(
                    line for line in (builder.ROOT / source_name).read_text(encoding="utf-8").splitlines() if line
                )
                positions.append(rendered.index(first_nonempty))
            self.assertEqual(positions, sorted(positions))
            self.assertTrue(rendered.endswith("})();\n"))


if __name__ == "__main__":
    unittest.main()
